name: Release DevTools Electron

on:
  workflow_dispatch:
  push:
    tags:
      - 'devtools-electron-v*'

permissions:
  contents: write

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build dependencies
        run: npm run build:core
      
      - name: Install Electron in workspace
        working-directory: packages/devtools-electron
        run: npm install electron@30.0.0 --save-dev

      - name: Build Panel UI
        run: npm run build --workspace=@cnstra/devtools-panel-ui

      - name: Copy Panel UI dist to electron package
        run: |
          mkdir -p packages/devtools-electron/resources
          cp -r packages/devtools-panel-ui/dist packages/devtools-electron/resources/devtools-panel-ui-dist

      - name: Generate icons
        run: npm run gen:icons --workspace=@cnstra/devtools-electron

      - name: Build mac dmg/zip (arm64 + x64)
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          CSC_IDENTITY_AUTO_DISCOVERY: true
        run: |
          npm run dist:mac --workspace=@cnstra/devtools-electron
          npx electron-builder --project packages/devtools-electron --mac dmg zip --x64

      - name: Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-artifacts
          path: |
            packages/devtools-electron/dist/*.dmg
            packages/devtools-electron/dist/*.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build dependencies
        run: npm run build:core
      
      - name: Install Electron in workspace
        working-directory: packages/devtools-electron
        run: npm install electron@30.0.0 --save-dev

      - name: Build Panel UI
        run: npm run build --workspace=@cnstra/devtools-panel-ui

      - name: Copy Panel UI dist to electron package
        run: |
          New-Item -ItemType Directory -Force -Path packages/devtools-electron/resources
          Copy-Item -Recurse packages/devtools-panel-ui/dist packages/devtools-electron/resources/devtools-panel-ui-dist

      - name: Build windows exe
        run: npm run dist:win --workspace=@cnstra/devtools-electron

      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: packages/devtools-electron/dist/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build dependencies
        run: npm run build:core
      
      - name: Install Electron in workspace
        working-directory: packages/devtools-electron
        run: npm install electron@30.0.0 --save-dev

      - name: Build Panel UI
        run: npm run build --workspace=@cnstra/devtools-panel-ui

      - name: Copy Panel UI dist to electron package
        run: |
          mkdir -p packages/devtools-electron/resources
          cp -r packages/devtools-panel-ui/dist packages/devtools-electron/resources/devtools-panel-ui-dist

      - name: Build linux AppImage
        run: npm run dist:linux --workspace=@cnstra/devtools-electron

      - name: Upload linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: packages/devtools-electron/dist/*.AppImage

  release:
    needs: [build-mac, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts -type f

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            artifacts/mac-artifacts/*
            artifacts/windows-artifacts/*
            artifacts/linux-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


